#!/bin/bash

# Launches ${project.artifactId} on MacOS as an app.

HERE=$(cd "$(dirname "$0")"; pwd)

RES="${HERE}/../Resources/Java/repo"

# Our JVM, not known if it exists or not
MYJAVA=${RES}/jre-x64-macOS/bin/java

# Set to the preferred Java VM, >= ${maven.compiler.target} required.
# If our own exists, use that, otherwise hope that it exists already
if [ -f "${MYJAVA}" ] ; then
    JAVA=${MYJAVA}
else
    JAVA=$(which java)
fi

# Cannot just give "$@" to the program, since double clicking stuffs junk in $@. Grrr...
if [ -f "$JAVA" ] && [ -x "$JAVA" ] ; then
    cd ${RES}
    exec "${JAVA}" -Xdock:icon="${RES}/${project.artifactId}.icns" -Xdock:name="${project.artifactId}" \
       -jar "${RES}/${project.artifactId}-${project.version}-jar-with-dependencies.jar" > "${HOME}/.${project.artifactId}.err" 2>&1
else
    # display error message with applescript
    osascript -e "tell application \"System Events\" to display dialog \"Error launching ${project.artifactId}.\n\nJava JDK (not just JRE) is needed.\nVisit http://java.com for more information...\" with title \"${project.artifactId}\" buttons {\" OK \"} default button 1"
    exit 1
fi
