/*
Copyright (C) 2016 Bengt Martensson.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program. If not, see http://www.gnu.org/licenses/.
*/

package org.harctoolbox.guicomponents;

import javax.swing.JPanel;
import org.harctoolbox.irscrutinizer.GuiMain;

public final class CapturingSendingBean extends javax.swing.JPanel {

    private GuiMain guiMain;
    private JPanel senderPanel;

    /**
     * Creates new form CapturingSendingPanel
     */
    public CapturingSendingBean() {
        this(null);
    }

    // Cannot set senderPanel here, because it may not be set up at the time
    // this constructor is called.
    public CapturingSendingBean(GuiMain guiMain) {
        this.guiMain = guiMain;
        this.senderPanel = null;
        initComponents();
    }

    public void setOpened(boolean opened) {
        openedLabel.setEnabled(opened);
    }

    public void setSenderPanel(JPanel panel) {
        this.senderPanel = panel;
        configureOpenButton.setEnabled(panel != null);
    }

    public void doJump() {
        guiMain.selectSenderHardware(senderPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        configureOpenButton = new javax.swing.JButton();
        openedLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        configureOpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Crystal-Clear/22x22/actions/goto.png"))); // NOI18N
        configureOpenButton.setText("Jump to Configure/Open");
        configureOpenButton.setToolTipText("Press to jump to the panel for configuring and opening.");
        configureOpenButton.setEnabled(false);
        configureOpenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configureOpenButtonActionPerformed(evt);
            }
        });

        openedLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/connect_established.png"))); // NOI18N
        openedLabel.setText("Device Opened");
        openedLabel.setEnabled(false);

        jLabel2.setText("This device can be used both for capturing and sending.");

        jLabel1.setText("It is configured and opened from the \"Sending hw\" pane.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(openedLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(configureOpenButton))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openedLabel)
                    .addComponent(configureOpenButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configureOpenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configureOpenButtonActionPerformed
        doJump();
    }//GEN-LAST:event_configureOpenButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configureOpenButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel openedLabel;
    // End of variables declaration//GEN-END:variables
}
