<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:output method="text"/>
    <xsl:strip-space elements="*"/>
    <xsl:preserve-space elements="source"/>

    <xsl:template match="/">
        <xsl:text>(This text has been extracted from the manual in XML format `IrScrutinizer.xml`. Do not edit this file.)

</xsl:text>
        <xsl:apply-templates select="document/body/section[@id='building-from-sources']"/>
    </xsl:template>

    <xsl:template match="section">
        <xsl:text># Building from sources

</xsl:text>
        <!--xsl:value-of select="title/text()"/-->
        <xsl:apply-templates select="*[not(name(.)='title')]"/>
    </xsl:template>

    <xsl:template match="section[count(ancestor::section)=1]">
        <xsl:text>## </xsl:text>
        <xsl:apply-templates select="*"/>
    </xsl:template>

    <xsl:template match="section[count(ancestor::section)=2]">
        <xsl:text>### </xsl:text>
        <xsl:apply-templates select="*"/>
    </xsl:template>

    <xsl:template match="section[count(ancestor::section)=3]">
        <xsl:text>### </xsl:text>
        <xsl:apply-templates select="*"/>
    </xsl:template>

    <xsl:template match="title">
        <xsl:value-of select="."/>
        <xsl:text>
</xsl:text>
    </xsl:template>

    <xsl:template match="p">
        <xsl:apply-templates select="node()"/>
        <xsl:text>

</xsl:text>
    </xsl:template>

    <xsl:template match="strong">
        <xsl:text>*</xsl:text>
        <xsl:value-of select="."/>
        <xsl:text>*</xsl:text>
    </xsl:template>

    <xsl:template match="source">
        <xsl:text>
    </xsl:text>
              <xsl:apply-templates/>
              <xsl:text>
</xsl:text>
    </xsl:template>

    <xsl:template match="a">
        <xsl:text>[</xsl:text>
        <xsl:value-of select="."/>
        <xsl:text>](</xsl:text>
        <xsl:apply-templates select="@href"/>
        <xsl:text>)</xsl:text>
    </xsl:template>

    <xsl:template match="@href">
        <xsl:value-of select="."/>
    </xsl:template>

    <!-- Fix up local references; they won't be local any more -->
    <xsl:template match="@href[substring(.,1,1)='#']">
        <xsl:text>http://harctoolbox.org/IrScrutinizer.html</xsl:text>
        <xsl:value-of select="."/>
    </xsl:template>

    <xsl:template match="code">
        <xsl:text>`</xsl:text>
        <xsl:value-of select="."/>
        <xsl:text>`</xsl:text>
    </xsl:template>

    <xsl:template match="em">
        <xsl:text>_</xsl:text>
        <xsl:value-of select="."/>
        <xsl:text>_</xsl:text>
    </xsl:template>

    <xsl:template match="ul">
        <xsl:text>
</xsl:text>
        <xsl:apply-templates select="*"/>
        <xsl:text>

</xsl:text>
    </xsl:template>

    <xsl:template match="li">
        <xsl:text>
* </xsl:text>
        <xsl:apply-templates/>
        <xsl:text>
</xsl:text>
    </xsl:template>

</xsl:stylesheet>
